from __future__ import annotations

# Source: E:\KESTRA\core\src\main\java\io\kestra\core\repositories\FlowRepositoryInterface.java
# WARNING: Unresolved types: ConstraintViolationException, Fields, Flux, Pageable

from typing import Any, Optional, Protocol

from engine.core.repositories.array_list_total import ArrayListTotal
from engine.core.models.executions.execution import Execution
from engine.core.models.executions.statistics.flow import Flow
from engine.core.models.flows.flow_for_execution import FlowForExecution
from engine.core.models.flows.flow_interface import FlowInterface
from engine.core.models.flows.flow_with_source import FlowWithSource
from engine.plugin.core.dashboard.data.flows import Flows
from engine.core.models.flows.generic_flow import GenericFlow
from engine.core.repositories.query_builder_interface import QueryBuilderInterface
from engine.core.models.query_filter import QueryFilter
from engine.core.models.search_result import SearchResult


class FlowRepositoryInterface(QueryBuilderInterface, Protocol):
    def find_by_id(self, tenant_id: str, namespace: str, id: str, revision: Optional[int], allow_deleted: bool) -> Optional[Flow]: ...

    def find_by_id(self, tenant_id: str, namespace: str, id: str, revision: Optional[int]) -> Optional[Flow]: ...

    def find_by_id_without_acl(self, tenant_id: str, namespace: str, id: str, revision: Optional[int]) -> Optional[Flow]: ...

    def is_namespace_exists(self, tenant: str, namespace: str) -> bool: ...

    def find_by_execution_without_acl(self, execution: Execution) -> FlowWithSource: ...

    def find_by_execution(self, execution: Execution) -> Flow: ...

    def find_by_execution_with_source(self, execution: Execution) -> FlowWithSource: ...

    def find_by_id(self, tenant_id: str, namespace: str, id: str) -> Optional[Flow]: ...

    def find_by_id_with_source(self, tenant_id: str, namespace: str, id: str, revision: Optional[int], allow_delete: bool) -> Optional[FlowWithSource]: ...

    def find_by_id_with_source(self, tenant_id: str, namespace: str, id: str, revision: Optional[int]) -> Optional[FlowWithSource]: ...

    def find_by_id_with_source(self, tenant_id: str, namespace: str, id: str) -> Optional[FlowWithSource]: ...

    def find_by_id_with_source_without_acl(self, tenant_id: str, namespace: str, id: str, revision: Optional[int]) -> Optional[FlowWithSource]: ...

    def find_revisions(self, tenant_id: str, namespace: str, id: str, allow_deleted: bool) -> list[FlowWithSource]: ...

    def find_revisions(self, tenant_id: str, namespace: str, id: str, allow_deleted: bool, revisions: list[int]) -> list[FlowWithSource]: ...

    def last_revision(self, tenant_id: str, namespace: str, id: str) -> int: ...

    def find_all(self, tenant_id: str) -> list[Flow]: ...

    def find_all_with_source(self, tenant_id: str) -> list[FlowWithSource]: ...

    def find_all_with_source_with_no_acl(self, tenant_id: str) -> list[FlowWithSource]: ...

    def find_all_for_all_tenants(self) -> list[Flow]: ...

    def find_all_with_source_for_all_tenants(self) -> list[FlowWithSource]: ...

    def count(self, tenant_id: str) -> int: ...

    def find_by_namespace(self, tenant_id: str, namespace: str) -> list[Flow]: ...

    def find_by_namespace_prefix(self, tenant_id: str, namespace_prefix: str) -> list[Flow]: ...

    def find_by_namespace_executable(self, tenant_id: str, namespace: str) -> list[FlowForExecution]: ...

    def find_by_namespace_with_source(self, tenant_id: str, namespace: str) -> list[FlowWithSource]: ...

    def find_by_namespace_prefix_with_source(self, tenant_id: str, namespace: str) -> list[FlowWithSource]: ...

    def find(self, pageable: Pageable, tenant_id: str, filters: list[QueryFilter]) -> ArrayListTotal[Flow]: ...

    def find_with_source(self, pageable: Pageable, tenant_id: str, filters: list[QueryFilter]) -> ArrayListTotal[FlowWithSource]: ...

    def find_source_code(self, pageable: Pageable, query: str, tenant_id: str, namespace: str) -> ArrayListTotal[SearchResult[Flow]]: ...

    def find_distinct_namespace(self, tenant_id: str) -> list[str]: ...

    def find_distinct_namespace_executable(self, tenant_id: str) -> list[str]: ...

    def find_distinct_namespace(self, tenant_id: str, prefix: str) -> list[str]: ...

    def find_async(self, tenant_id: str, filters: list[QueryFilter]) -> Flux[Flow]: ...

    def create(self, flow: GenericFlow) -> FlowWithSource: ...

    def update(self, flow: GenericFlow, previous: FlowInterface) -> FlowWithSource: ...

    def delete(self, flow: FlowInterface) -> FlowWithSource: ...

    def delete_revisions(self, tenant_id: str, namespace: str, id: str, revisions: list[int]) -> None: ...

    def exist_any_no_acl(self, tenant_id: str) -> bool: ...
