from __future__ import annotations

# Source: E:\KESTRA\core\src\main\java\io\kestra\core\repositories\LogRepositoryInterface.java

from datetime import datetime
from typing import Any, Protocol

from engine.core.repositories.array_list_total import ArrayListTotal
from engine.core.models.executions.execution import Execution
from engine.core.models.executions.log_entry import LogEntry
from engine.plugin.core.dashboard.data.logs import Logs
from engine.core.repositories.query_builder_interface import QueryBuilderInterface
from engine.core.models.query_filter import QueryFilter
from engine.core.repositories.save_repository_interface import SaveRepositoryInterface


class LogRepositoryInterface(SaveRepositoryInterface, QueryBuilderInterface, Protocol):
    def find_by_execution_id(self, tenant_id: str, namespace: str, flow_id: str, execution_id: str | None = None, min_level: int | None = None) -> list[LogEntry]: ...

    def find_by_execution_id_without_acl(self, tenant_id: str, execution_id: str, min_level: int) -> list[LogEntry]: ...

    def find_by_execution_id_and_task_id(self, tenant_id: str, namespace: str, flow_id: str, execution_id: str, task_id: str | None = None, min_level: int | None = None) -> list[LogEntry]: ...

    def find_by_execution_id_and_task_id_without_acl(self, tenant_id: str, execution_id: str, task_id: str, min_level: int) -> list[LogEntry]: ...

    def find_by_execution_id_and_task_run_id(self, tenant_id: str, execution_id: str, task_run_id: str, min_level: int, pageable: Pageable | None = None) -> ArrayListTotal[LogEntry]: ...

    def find_by_execution_id_and_task_run_id_without_acl(self, tenant_id: str, execution_id: str, task_run_id: str, min_level: int) -> list[LogEntry]: ...

    def find_by_execution_id_and_task_run_id_and_attempt(self, tenant_id: str, execution_id: str, task_run_id: str, min_level: int, attempt: int, pageable: Pageable | None = None) -> ArrayListTotal[LogEntry]: ...

    def find_by_execution_id_and_task_run_id_and_attempt_without_acl(self, tenant_id: str, execution_id: str, task_run_id: str, min_level: int, attempt: int) -> list[LogEntry]: ...

    def find(self, pageable: Pageable, tenant_id: str, filters: list[QueryFilter]) -> ArrayListTotal[LogEntry]: ...

    def find_async(self, tenant_id: str, filters: list[QueryFilter]) -> Flux[LogEntry]: ...

    def find_all_async(self, tenant_id: str) -> Flux[LogEntry]: ...

    def save(self, log: LogEntry) -> LogEntry: ...

    def purge(self, execution: Execution) -> int: ...

    def delete_by_query(self, tenant_id: str, namespace: str, flow_id: str, execution_id: str, log_levels: list[int] | None = None, start_date: datetime | None = None, end_date: datetime | None = None) -> int: ...

    def delete_by_filters(self, tenant_id: str, filters: list[QueryFilter]) -> None: ...
