from __future__ import annotations

# Source: E:\KESTRA\core\src\main\java\io\kestra\core\repositories\TemplateRepositoryInterface.java
# WARNING: Unresolved types: Pageable

from typing import Any, Protocol

from engine.core.repositories.array_list_total import ArrayListTotal
from engine.core.models.templates.template import Template


class TemplateRepositoryInterface(Protocol):
    def find_by_id(self, tenant_id: str, namespace: str, id: str) -> Optional[Template]: ...

    def find_all(self, tenant_id: str) -> list[Template]: ...

    def find_all_with_no_acl(self, tenant_id: str) -> list[Template]: ...

    def find_all_for_all_tenants(self) -> list[Template]: ...

    def find(self, pageable: Pageable, query: str, tenant_id: str, namespace: str) -> ArrayListTotal[Template]: ...

    def find(self, query: str, tenant_id: str, namespace: str) -> list[Template]: ...

    def find_by_namespace(self, tenant_id: str, namespace: str) -> list[Template]: ...

    def create(self, template: Template) -> Template: ...

    def update(self, template: Template, previous: Template) -> Template: ...

    def delete(self, template: Template) -> None: ...

    def find_distinct_namespace(self, tenant_id: str) -> list[str]: ...
