from __future__ import annotations

# Source: E:\KESTRA\core\src\main\java\io\kestra\core\repositories\TriggerRepositoryInterface.java
# WARNING: Unresolved types: Fields, Flux, Function, IllegalArgumentException, Pageable

from typing import Any, Protocol

from engine.core.repositories.array_list_total import ArrayListTotal
from engine.core.repositories.query_builder_interface import QueryBuilderInterface
from engine.core.models.query_filter import QueryFilter
from engine.core.models.triggers.trigger import Trigger
from engine.core.models.triggers.trigger_context import TriggerContext
from engine.plugin.core.dashboard.data.triggers import Triggers


class TriggerRepositoryInterface(Protocol):
    def find_last(self, trigger: TriggerContext) -> Optional[Trigger]: ...

    def find_by_uid(self, uid: str) -> Optional[Trigger]: ...

    def find_all(self, tenant_id: str) -> list[Trigger]: ...

    def find_all_for_all_tenants(self) -> list[Trigger]: ...

    def save(self, trigger: Trigger) -> Trigger: ...

    def delete(self, trigger: Trigger) -> None: ...

    def update(self, trigger: Trigger) -> Trigger: ...

    def lock(self, trigger_uid: str, function: Function[Trigger, Trigger]) -> Trigger: ...

    def find(self, from: Pageable, query: str, tenant_id: str, namespace: str, flow_id: str, worker_id: str) -> ArrayListTotal[Trigger]: ...

    def find(self, from: Pageable, tenant_id: str, filters: list[QueryFilter]) -> ArrayListTotal[Trigger]: ...

    def count_all(self, tenant_id: str) -> int: ...

    def find_async(self, tenant_id: str, filters: list[QueryFilter]) -> Flux[Trigger]: ...

    def sort_mapping(self) -> Function[str, str]: ...
