from __future__ import annotations

from typing import Any, Protocol

from engine.core.models.property.property import Property


class SolaceConnectionInterface(Protocol):
    def get_username(self) -> Property[str]: ...
    def get_password(self) -> Property[str]: ...
    def get_vpn(self) -> Property[str]: ...
    def get_host(self) -> Property[str]: ...
    def get_properties(self) -> Property[dict[String, String]]: ...
