steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$_IMAGE_NAME'
      - '-f'
      - 'services/platform-api/Dockerfile'
      - 'services/platform-api'
images:
  - '$_IMAGE_NAME'