from __future__ import annotations

from typing import Any, Protocol

from engine.core.models.property.property import Property


class SftpInterface(Protocol):
    def get_keyfile(self) -> Property[str]: ...
    def get_passphrase(self) -> Property[str]: ...
    def get_proxy_host(self) -> Property[str]: ...
    def get_proxy_address(self) -> Property[str]: ...
    def get_proxy_port(self) -> Property[str]: ...
    def get_proxy_user(self) -> Property[str]: ...
    def get_proxy_username(self) -> Property[str]: ...
    def get_proxy_password(self) -> Property[str]: ...
    def get_proxy_type(self) -> Property[str]: ...
    def get_root_dir(self) -> Property[bool]: ...
    def get_key_exchange_algorithm(self) -> Property[str]: ...
