from __future__ import annotations

from typing import Any, Protocol

from integrations.azure.eventhubs.event_hub_client_interface import EventHubClientInterface
from engine.core.models.property.property import Property
from integrations.solace.serde.serdes import Serdes
from integrations.azure.eventhubs.service.consumer.starting_position import StartingPosition


class EventHubConsumerInterface(EventHubClientInterface):
    def get_body_deserializer(self) -> Property[Serdes]: ...
    def get_body_deserializer_properties(self) -> Property[dict[String, Object]]: ...
    def get_consumer_group(self) -> Property[str]: ...
    def get_partition_starting_position(self) -> Property[StartingPosition]: ...
    def get_enqueue_time(self) -> Property[str]: ...
    def get_checkpoint_store_properties(self) -> Property[dict[String, String]]: ...
