from __future__ import annotations

from typing import Any, Protocol

from engine.core.models.property.property import Property


class AmqpConnectionInterface(Protocol):
    def get_url(self) -> Property[str]: ...
    def get_host(self) -> Property[str]: ...
    def get_port(self) -> Property[str]: ...
    def get_virtual_host(self) -> Property[str]: ...
    def get_username(self) -> Property[str]: ...
    def get_password(self) -> Property[str]: ...
