param(
    [int]$TimeoutSeconds = 300,
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"

function Load-EnvFile([string]$path) {
    if (-not (Test-Path $path)) { return }
    Get-Content $path | ForEach-Object {
        if ($_ -match '^\s*([A-Z_][A-Z0-9_]*)=(.*)$' -and $_ -notmatch '^\s*#') {
            [Environment]::SetEnvironmentVariable($Matches[1], $Matches[2], "Process")
        }
    }
}

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
Load-EnvFile (Join-Path $repoRoot ".env")

$required = @("TEST_EMAIL", "TEST_PASSWORD", "SUPABASE_ANON_KEY")
$missing = @(
    $required | Where-Object {
        $value = [Environment]::GetEnvironmentVariable($_, "Process")
        [string]::IsNullOrWhiteSpace($value)
    }
)
if ($missing.Count -gt 0) {
    throw "Missing required env var(s) for non-interactive smoke runs: $($missing -join ', ')"
}

$smokeScript = Join-Path $PSScriptRoot "smoke-test-non-md.ps1"
if (-not (Test-Path $smokeScript)) {
    throw "Smoke script not found: $smokeScript"
}

$timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
$logsDir = Join-Path $PSScriptRoot "logs"
New-Item -ItemType Directory -Force -Path $logsDir | Out-Null

$tmpHtml = Join-Path $PSScriptRoot "_tmp-smoke.html"
$tmpCsv = Join-Path $PSScriptRoot "_tmp-smoke.csv"

# Minimal fixtures for HTML/CSV where repo fixture files are not committed.
"<html><body><h1>Smoke</h1><p>HTML format smoke test.</p></body></html>" | Out-File -FilePath $tmpHtml -Encoding utf8
"col_a,col_b`nhello,123" | Out-File -FilePath $tmpCsv -Encoding utf8

$formatFixtures = @(
    @{ format = "md"; file = Join-Path $repoRoot "docs/tests/test-pack/gfm-smoke.md" },
    @{ format = "txt"; file = Join-Path $repoRoot "scripts/test-non-md.txt" },
    @{ format = "docx"; file = Join-Path $repoRoot "docs/tests/test-pack/lorem_ipsum.docx" },
    @{ format = "pdf"; file = Join-Path $repoRoot "docs/tests/test-pack/lorem_ipsum.pdf" },
    @{ format = "pptx"; file = Join-Path $repoRoot "docs/tests/test-pack/lorem_ipsum.pptx" },
    @{ format = "xlsx"; file = Join-Path $repoRoot "docs/tests/test-pack/lorem_ipsum.xlsx" },
    @{ format = "html"; file = $tmpHtml },
    @{ format = "csv"; file = $tmpCsv }
)

$rows = New-Object System.Collections.Generic.List[object]

foreach ($entry in $formatFixtures) {
    $fmt = $entry.format
    $file = $entry.file
    $logPath = Join-Path $logsDir "smoke-$fmt-$timestamp.log"

    if (-not (Test-Path $file)) {
        $rows.Add([pscustomobject]@{
            Format = $fmt
            Fixture = $file
            Result = "SKIPPED (missing fixture)"
            ExitCode = ""
            Log = ""
        })
        continue
    }

    if ($DryRun) {
        $rows.Add([pscustomobject]@{
            Format = $fmt
            Fixture = $file
            Result = "DRY-RUN"
            ExitCode = ""
            Log = $logPath
        })
        continue
    }

    Write-Host "Running smoke for $fmt using $file" -ForegroundColor Cyan

    $output = & powershell -NoProfile -ExecutionPolicy Bypass -File $smokeScript `
        -FilePath $file `
        -DocTitle "Format smoke: $fmt" `
        -TimeoutSeconds $TimeoutSeconds 2>&1

    $exitCode = $LASTEXITCODE
    ($output | Out-String) | Out-File -FilePath $logPath -Encoding utf8

    $result = if ($exitCode -eq 0) { "PASS" } else { "FAIL" }
    $rows.Add([pscustomobject]@{
        Format = $fmt
        Fixture = $file
        Result = $result
        ExitCode = $exitCode
        Log = $logPath
    })
}

$reportPath = Join-Path $repoRoot "docs/ongoing-tasks/0211-source-format-smoke-results.md"
$lines = @()
$lines += "# Source Format Smoke Results ($timestamp)"
$lines += ""
$lines += "| Format | Result | ExitCode | Fixture | Log |"
$lines += "|---|---|---:|---|---|"
foreach ($r in $rows) {
    $fixtureRel = $r.Fixture.Replace($repoRoot + "\", "")
    $logRel = if ($r.Log) { $r.Log.Replace($repoRoot + "\", "") } else { "" }
    $lines += "| $($r.Format) | $($r.Result) | $($r.ExitCode) | $fixtureRel | $logRel |"
}
$lines += ""
$lines += "Generated by `scripts/run-format-matrix-smoke.ps1`."
$lines | Out-File -FilePath $reportPath -Encoding utf8

Remove-Item $tmpHtml -ErrorAction SilentlyContinue
Remove-Item $tmpCsv -ErrorAction SilentlyContinue

Write-Host "Report written to: $reportPath" -ForegroundColor Green
Write-Host "Done." -ForegroundColor Green
