from __future__ import annotations

# Source: E:\KESTRA\core\src\main\java\io\kestra\core\plugins\PluginRegistry.java
# WARNING: Unresolved types: Class, Predicate

from pathlib import Path
from typing import Any, Optional, Protocol

from engine.core.models.plugin import Plugin
from engine.core.plugins.plugin_class_and_metadata import PluginClassAndMetadata
from engine.core.plugins.plugin_identifier import PluginIdentifier
from engine.core.plugins.registered_plugin import RegisteredPlugin


class PluginRegistry(Protocol):
    def get_all_versions_for_type(self, type: str) -> list[str]: ...

    def register_if_absent(self, plugin_path: Path) -> None: ...

    def register(self, plugin_path: Path) -> None: ...

    def unregister(self, plugin: list[RegisteredPlugin]) -> None: ...

    def register_class_for_identifier(self, identifier: PluginIdentifier, plugin: PluginClassAndMetadata[Any]) -> None: ...

    def find_class_by_identifier(self, identifier: PluginIdentifier) -> Class[Any]: ...

    def find_class_by_identifier(self, identifier: str) -> Class[Any]: ...

    def find_metadata_by_identifier(self, identifier: str) -> Optional[PluginClassAndMetadata[Any]]: ...

    def find_metadata_by_identifier(self, identifier: PluginIdentifier) -> Optional[PluginClassAndMetadata[Any]]: ...

    def plugins(self) -> list[RegisteredPlugin]: ...

    def plugins(self, predicate: Predicate[RegisteredPlugin]) -> list[RegisteredPlugin]: ...

    def external_plugins(self) -> list[RegisteredPlugin]: ...

    def clear(self) -> None: ...

    def is_versioning_supported(self) -> bool: ...

    def hash(self) -> int: ...
