from __future__ import annotations

# Source: E:\KESTRA\core\src\main\java\io\kestra\core\models\tasks\runners\TaskCommands.java
# WARNING: Unresolved types: IOException

from pathlib import Path
from datetime import timedelta
from typing import Any, Protocol

from engine.core.models.tasks.runners.abstract_log_consumer import AbstractLogConsumer
from engine.core.models.property.property import Property
from engine.core.models.tasks.runners.target_os import TargetOS


class TaskCommands(Protocol):
    def get_container_image(self) -> str: ...

    def get_log_consumer(self) -> AbstractLogConsumer: ...

    def get_interpreter(self) -> Property[list[str]]: ...

    def get_before_commands(self) -> Property[list[str]]: ...

    def get_commands(self) -> Property[list[str]]: ...

    def get_additional_vars(self) -> dict[str, Any]: ...

    def output_directory_name(self) -> str: ...

    def get_working_directory(self) -> Path: ...

    def get_output_directory(self) -> Path: ...

    def get_env(self) -> dict[str, str]: ...

    def get_enable_output_directory(self) -> bool: ...

    def output_directory_enabled(self) -> bool: ...

    def get_timeout(self) -> timedelta: ...

    def get_target_os(self) -> TargetOS: ...

    def relative_working_directory_files_paths(self) -> list[Path]: ...

    def relative_working_directory_files_paths(self, include_directories: bool) -> list[Path]: ...
