from __future__ import annotations

from typing import Any, Protocol

from integrations.mqtt.abstract_mqtt_connection import AbstractMqttConnection
from integrations.mqtt.services.message import Message
from engine.plugin.core.metric.publish import Publish
from engine.core.runners.run_context import RunContext
from integrations.mqtt.subscribe import Subscribe


class MqttInterface(Protocol):
    def connect(self, run_context: RunContext, connection: AbstractMqttConnection) -> None: ...
    def publish(self, run_context: RunContext, publish: Publish, message: byte) -> None: ...
    def subscribe(self, run_context: RunContext, subscribe: Subscribe, consumer: Consumer[Message]) -> None: ...
    def unsubscribe(self, run_context: RunContext, subscribe: Subscribe) -> None: ...
    def close(self) -> None: ...
    def on_disconnected(self, handler: Consumer[Throwable]) -> None: ...
    def create(self, version: AbstractMqttConnection) -> MqttInterface: ...
