from __future__ import annotations

# Source: E:\KESTRA\core\src\main\java\io\kestra\core\models\flows\FlowInterface.java
# WARNING: Unresolved types: ObjectMapper, Pattern

from dataclasses import dataclass, field
from typing import Any, ClassVar, Protocol

from engine.core.models.flows.concurrency import Concurrency
from engine.core.models.flows.flow_id import FlowId
from engine.core.models.flows.generic_flow import GenericFlow
from engine.core.models.has_source import HasSource
from engine.core.models.has_uid import HasUID
from engine.core.models.flows.input import Input
from engine.core.models.label import Label
from engine.core.models.flows.output import Output
from engine.core.models.flows.sla.sla import SLA
from engine.core.models.soft_deletable import SoftDeletable
from engine.core.models.tenant_interface import TenantInterface
from engine.core.models.tasks.worker_group import WorkerGroup


class FlowInterface(FlowId, SoftDeletable, TenantInterface, HasUID, HasSource, Protocol):
    def get_description(self) -> str: ...

    def is_disabled(self) -> bool: ...

    def is_deleted(self) -> bool: ...

    def get_labels(self) -> list[Label]: ...

    def get_inputs(self) -> list[Input[Any]]: ...

    def get_outputs(self) -> list[Output]: ...

    def get_variables(self) -> dict[str, Any]: ...

    def get_worker_group(self) -> WorkerGroup: ...

    def get_concurrency(self) -> Concurrency: ...

    def get_sla(self) -> list[SLA]: ...

    def get_source(self) -> str: ...

    def source(self) -> str: ...

    def uid(self) -> str: ...

    def uid_without_revision(self) -> str: ...

    def is_same_with_source(self, flow: FlowInterface) -> bool: ...

    def is_same_id(self, that: FlowId) -> bool: ...

    def source_without_revision(source: str) -> str: ...

    def source_or_generate_if_null(self) -> str: ...
