from __future__ import annotations

# Source: E:\KESTRA\core\src\main\java\io\kestra\core\models\flows\FlowId.java

from dataclasses import dataclass
from typing import Any, Optional, Protocol

from engine.core.models.executions.execution import Execution
from engine.core.models.triggers.trigger import Trigger


class FlowId(Protocol):
    def get_id(self) -> str: ...

    def get_namespace(self) -> str: ...

    def get_revision(self) -> int: ...

    def get_tenant_id(self) -> str: ...

    def uid(flow: FlowId) -> str: ...

    def uid(tenant_id: str, namespace: str, id: str, revision: Optional[int]) -> str: ...

    def uid_without_revision(flow: FlowId) -> str: ...

    def uid_without_revision(tenant_id: str, namespace: str, id: str) -> str: ...

    def uid(trigger: Trigger) -> str: ...

    def uid_without_revision(execution: Execution) -> str: ...

    def of(tenant_id: str, namespace: str, id: str, revision: int) -> FlowId: ...
