from __future__ import annotations

# Source: E:\KESTRA-IO\plugins\plugin-aws\src\main\java\io\kestra\plugin\aws\AbstractConnectionInterface.java
# WARNING: Unresolved types: AwsClientConfig

from datetime import timedelta
from typing import Any, Protocol

from integrations.aws.abstract_connection import AbstractConnection
from engine.core.exceptions.illegal_variable_evaluation_exception import IllegalVariableEvaluationException
from engine.core.models.property.property import Property
from engine.core.runners.run_context import RunContext


class AbstractConnectionInterface(Protocol):
    def get_access_key_id(self) -> Property[str]: ...

    def get_secret_key_id(self) -> Property[str]: ...

    def get_session_token(self) -> Property[str]: ...

    def get_sts_role_arn(self) -> Property[str]: ...

    def get_sts_role_external_id(self) -> Property[str]: ...

    def get_sts_role_session_name(self) -> Property[str]: ...

    def get_sts_role_session_duration(self) -> Property[timedelta]: ...

    def get_sts_endpoint_override(self) -> Property[str]: ...

    def get_region(self) -> Property[str]: ...

    def get_endpoint_override(self) -> Property[str]: ...

    def get_compatibility_mode(self) -> Property[bool]: ...

    def get_force_path_style(self) -> Property[bool]: ...

    def aws_client_config(self, run_context: RunContext) -> AbstractConnection.AwsClientConfig: ...
