from __future__ import annotations

# Source: E:\KESTRA\core\src\main\java\io\kestra\core\storages\Namespace.java
# WARNING: Unresolved types: Exception, IOException, InputStream, Pageable, Pair, Predicate, URISyntaxException

from enum import Enum
from pathlib import Path
from typing import Any, Protocol

from engine.core.repositories.array_list_total import ArrayListTotal
from engine.core.models.fetch_version import FetchVersion
from engine.core.storages.file_attributes import FileAttributes
from engine.core.storages.namespace_file import NamespaceFile
from engine.core.models.namespaces.files.namespace_file_metadata import NamespaceFileMetadata
from engine.core.models.query_filter import QueryFilter


class Namespace(Protocol):
    def find(self, pageable: Pageable, filters: list[QueryFilter], allow_deleted: bool, fetch_version: FetchVersion) -> ArrayListTotal[NamespaceFile]: ...

    def namespace(self) -> str: ...

    def tenant_id(self) -> str: ...

    def all(self) -> list[NamespaceFile]: ...

    def all(self, containing: str) -> list[NamespaceFile]: ...

    def all(self, containing: str, include_directories: bool) -> list[NamespaceFile]: ...

    def children(self, parent_path: str, recursive: bool) -> list[NamespaceFileMetadata]: ...

    def move(self, source: Path, target: Path) -> list[Pair[NamespaceFile, NamespaceFile]]: ...

    def get(self, path: Path) -> NamespaceFile: ...

    def find_all_files_matching(self, predicate: Predicate[Path]) -> list[NamespaceFile]: ...

    def find_all_files_matching(self, includes: list[str], excludes: list[str]) -> list[NamespaceFile]: ...

    def get_file_content(self, path: Path) -> InputStream: ...

    def get_file_content(self, path: Path, version: int) -> InputStream: ...

    def get_file_metadata(self, path: Path) -> FileAttributes: ...

    def exists(self, path: Path) -> bool: ...

    def put_file(self, path: Path, content: InputStream) -> list[NamespaceFile]: ...

    def put_file(self, path: Path, content: InputStream, on_already_exist: Conflicts) -> list[NamespaceFile]: ...

    def put_file(self, file: NamespaceFile, content: InputStream) -> list[NamespaceFile]: ...

    def put_file(self, file: NamespaceFile, content: InputStream, on_already_exist: Conflicts) -> list[NamespaceFile]: ...

    def create_directory(self, path: Path) -> NamespaceFile: ...

    def delete(self, file: NamespaceFile) -> list[NamespaceFile]: ...

    def delete(self, path: Path) -> list[NamespaceFile]: ...

    def purge(self, namespace_file: NamespaceFile) -> bool: ...

    def purge(self, namespace_files: list[NamespaceFile]) -> int: ...

    def is_directory_empty(self, path: str) -> bool: ...
