from __future__ import annotations

# Source: E:\KESTRA\core\src\main\java\io\kestra\core\storages\Storage.java
# WARNING: Unresolved types: IOException, InputStream

from pathlib import Path
from datetime import timedelta
from typing import Any, Optional, Protocol

from engine.core.storages.file_attributes import FileAttributes
from engine.core.models.namespaces.namespace import Namespace
from engine.core.storages.storage_context import StorageContext
from engine.core.models.tasks.task import Task


class Storage(Protocol):
    def namespace(self) -> Namespace: ...

    def namespace(self, namespace: str) -> Namespace: ...

    def is_file_exist(self, uri: str) -> bool: ...

    def get_file(self, uri: str) -> InputStream: ...

    def get_attributes(self, uri: str) -> FileAttributes: ...

    def delete_file(self, uri: str) -> bool: ...

    def delete_execution_files(self) -> list[str]: ...

    def get_context_base_u_r_i(self) -> str: ...

    def put_file(self, input_stream: InputStream, name: str) -> str: ...

    def put_file(self, input_stream: InputStream, uri: str) -> str: ...

    def put_file(self, file: Path) -> str: ...

    def put_file(self, file: Path, name: str) -> str: ...

    def get_cache_file(self, cache_id: str, object_id: str) -> Optional[InputStream]: ...

    def get_cache_file(self, cache_id: str, object_id: str, ttl: timedelta) -> Optional[InputStream]: ...

    def put_cache_file(self, file: Path, cache_id: str, object_id: str) -> str: ...

    def delete_cache_file(self, cache_id: str, object_id: str) -> Optional[bool]: ...

    def get_task_storage_context(self) -> Optional[StorageContext.Task]: ...

    def list(self, uri: str) -> list[FileAttributes]: ...
