from __future__ import annotations

# Source: E:\KESTRA\core\src\main\java\io\kestra\core\storages\StorageInterface.java
# WARNING: Unresolved types: AutoCloseable, FileNotFoundException, IOException, InputStream, NoSuchFileException

from pathlib import Path
from typing import Any, Protocol

from engine.core.models.executions.execution import Execution
from engine.core.storages.file_attributes import FileAttributes
from engine.core.models.plugin import Plugin
from engine.core.storages.storage_object import StorageObject


class StorageInterface(Protocol):
    def init(self) -> None: ...

    def close(self) -> None: ...

    def get(self, tenant_id: str, namespace: str, uri: str) -> InputStream: ...

    def get_instance_resource(self, namespace: str, uri: str) -> InputStream: ...

    def get_with_metadata(self, tenant_id: str, namespace: str, uri: str) -> StorageObject: ...

    def all_by_prefix(self, tenant_id: str, namespace: str, prefix: str, include_directories: bool) -> list[str]: ...

    def list(self, tenant_id: str, namespace: str, uri: str) -> list[FileAttributes]: ...

    def list_instance_resource(self, namespace: str, uri: str) -> list[FileAttributes]: ...

    def exists(self, tenant_id: str, namespace: str, uri: str) -> bool: ...

    def exists_instance_resource(self, namespace: str, uri: str) -> bool: ...

    def get_attributes(self, tenant_id: str, namespace: str, uri: str) -> FileAttributes: ...

    def get_instance_attributes(self, namespace: str, uri: str) -> FileAttributes: ...

    def put(self, tenant_id: str, namespace: str, uri: str, data: InputStream) -> str: ...

    def put(self, tenant_id: str, namespace: str, uri: str, storage_object: StorageObject) -> str: ...

    def put_instance_resource(self, namespace: str, uri: str, data: InputStream) -> str: ...

    def put_instance_resource(self, namespace: str, uri: str, storage_object: StorageObject) -> str: ...

    def delete(self, tenant_id: str, namespace: str, uri: str) -> bool: ...

    def delete_instance_resource(self, namespace: str, uri: str) -> bool: ...

    def create_directory(self, tenant_id: str, namespace: str, uri: str) -> str: ...

    def create_instance_directory(self, namespace: str, uri: str) -> str: ...

    def move(self, tenant_id: str, namespace: str, from: str, to: str) -> str: ...

    def delete_by_prefix(self, tenant_id: str, namespace: str, storage_prefix: str) -> list[str]: ...

    def from(self, execution: Execution, input: str, file_name: str, file: Path) -> str: ...

    def parent_traversal_guard(self, uri: str) -> None: ...

    def get_path(self, uri: str) -> str: ...

    def get_path(self, tenant_id: str, uri: str) -> str: ...

    def limit(self, uri: str, max_object_name_length: int) -> str: ...
