from __future__ import annotations

# Source: E:\KESTRA\core\src\main\java\io\kestra\core\queues\QueueInterface.java
# WARNING: Unresolved types: Class, Closeable, Consumer, Runnable, T

from typing import Any, Protocol

from engine.core.exceptions.deserialization_exception import DeserializationException
from engine.core.utils.either import Either
from engine.core.models.pauseable import Pauseable
from engine.core.queues.queue_exception import QueueException


class QueueInterface(Closeable, Pauseable, Protocol):
    def emit(self, message: T) -> None: ...

    def emit(self, consumer_group: str, message: T) -> None: ...

    def emit_async(self, message: T) -> None: ...

    def emit_async(self, consumer_group: str, message: T) -> None: ...

    def emit_async(self, messages: list[T]) -> None: ...

    def emit_only(self, message: T) -> None: ...

    def emit_only(self, consumer_group: str, message: T) -> None: ...

    def emit_async(self, consumer_group: str, messages: list[T]) -> None: ...

    def delete(self, message: T) -> None: ...

    def delete(self, consumer_group: str, message: T) -> None: ...

    def receive(self, consumer: Consumer[Either[T, DeserializationException]]) -> Runnable: ...

    def receive(self, consumer_group: str, consumer: Consumer[Either[T, DeserializationException]]) -> Runnable: ...

    def receive(self, consumer_group: str, consumer: Consumer[Either[T, DeserializationException]], for_update: bool) -> Runnable: ...

    def receive(self, queue_type: Class[Any], consumer: Consumer[Either[T, DeserializationException]]) -> Runnable: ...

    def receive(self, consumer_group: str, queue_type: Class[Any], consumer: Consumer[Either[T, DeserializationException]]) -> Runnable: ...

    def receive(self, consumer_group: str, queue_type: Class[Any], consumer: Consumer[Either[T, DeserializationException]], for_update: bool) -> Runnable: ...
