from __future__ import annotations

# Source: E:\KESTRA\core\src\main\java\io\kestra\core\storages\kv\KVStore.java
# WARNING: Unresolved types: IOException, Pageable, Pattern, UncheckedIOException

from typing import Any, Protocol

from engine.core.repositories.array_list_total import ArrayListTotal
from engine.core.models.fetch_version import FetchVersion
from engine.core.storages.kv.k_v_entry import KVEntry
from engine.core.storages.kv.k_v_value import KVValue
from engine.core.storages.kv.k_v_value_and_metadata import KVValueAndMetadata
from engine.core.models.query_filter import QueryFilter
from engine.core.exceptions.resource_expired_exception import ResourceExpiredException


class KVStore(Protocol):
    def namespace(self) -> str: ...

    def storage_uri(self, key: str) -> str: ...

    def storage_uri(self, key: str, version: int) -> str: ...

    def storage_uri(self, key: str, namespace: str, version: int) -> str: ...

    def kv_file_name(key: str, version: int) -> str: ...

    def put(self, key: str, value: KVValueAndMetadata) -> None: ...

    def put(self, key: str, value: KVValueAndMetadata, overwrite: bool) -> None: ...

    def get_value(self, key: str) -> Optional[KVValue]: ...

    def delete(self, key: str) -> bool: ...

    def purge(self, kv_to_delete: list[KVEntry]) -> int: ...

    def list(self) -> ArrayListTotal[KVEntry]: ...

    def list(self, pageable: Pageable) -> ArrayListTotal[KVEntry]: ...

    def list(self, pageable: Pageable, query_filters: list[QueryFilter]) -> ArrayListTotal[KVEntry]: ...

    def list(self, pageable: Pageable, query_filters: list[QueryFilter], allow_deleted: bool, allow_expired: bool, fetch_behavior: FetchVersion) -> ArrayListTotal[KVEntry]: ...

    def list_all(self) -> list[KVEntry]: ...

    def get(self, key: str) -> Optional[KVEntry]: ...

    def exists(self, key: str) -> bool: ...

    def find_metadata_and_value(self, key: str) -> Optional[KVValueAndMetadata]: ...

    def validate_key(key: str) -> None: ...
