from __future__ import annotations

# Source: E:\KESTRA\core\src\main\java\io\kestra\core\runners\WorkingDir.java
# WARNING: Unresolved types: IOException, InputStream

from pathlib import Path
from typing import Any, Protocol

from engine.core.models.tasks.file_exist_comportment import FileExistComportment


class WorkingDir(Protocol):
    def path(self) -> Path: ...

    def path(self, create: bool) -> Path: ...

    def id(self) -> str: ...

    def resolve(self, path: Path) -> Path: ...

    def create_temp_file(self) -> Path: ...

    def create_temp_file(self, extension: str) -> Path: ...

    def create_temp_file(self, content: list[int]) -> Path: ...

    def create_temp_file(self, content: list[int], extension: str) -> Path: ...

    def create_file(self, filename: str) -> Path: ...

    def create_file(self, filename: str, content: list[int]) -> Path: ...

    def create_file(self, filename: str, content: InputStream) -> Path: ...

    def put_file(self, path: Path, content: InputStream) -> Path: ...

    def put_file(self, path: Path, content: InputStream, comportment: FileExistComportment) -> Path: ...

    def find_all_files_matching(self, patterns: list[str]) -> list[Path]: ...

    def cleanup(self) -> None: ...
