from __future__ import annotations

from typing import Any, Protocol
from datetime import timedelta

from integrations.jenkins.job_info import JobInfo
from engine.core.models.property.property import Property


class AbstractJobInterface(Protocol):
    def get_destination_table(self) -> Property[str]: ...
    def get_write_disposition(self) -> Property[JobInfo]: ...
    def get_create_disposition(self) -> Property[JobInfo]: ...
    def get_job_timeout(self) -> Property[timedelta]: ...
    def get_labels(self) -> Property[dict[String, String]]: ...
    def get_dry_run(self) -> Property[bool]: ...
