from __future__ import annotations

from typing import Any, Protocol

from engine.core.models.property.property import Property


class SurrealDBConnectionInterface(Protocol):
    def get_use_tls(self) -> Property[bool]: ...
    def get_connection_timeout(self) -> int: ...
    def get_port(self) -> int: ...
    def get_host(self) -> str: ...
    def get_username(self) -> Property[str]: ...
    def get_password(self) -> Property[str]: ...
    def get_namespace(self) -> str: ...
    def get_database(self) -> str: ...
