from __future__ import annotations

from enum import Enum
from typing import Any, Protocol

from engine.core.models.property.property import Property


class AuthMethod(str, Enum):
    PASSWORD = "PASSWORD"
    PUBLIC_KEY = "PUBLIC_KEY"
    OPEN_SSH = "OPEN_SSH"


class SshInterface(Protocol):
    def get_host(self) -> Property[str]: ...
    def get_port(self) -> Property[str]: ...
    def get_auth_method(self) -> Property[AuthMethod]: ...
    def get_username(self) -> Property[str]: ...
    def get_password(self) -> Property[str]: ...
    def get_private_key(self) -> Property[str]: ...
    def get_private_key_passphrase(self) -> Property[str]: ...
    def get_open_s_s_h_config_dir(self) -> Property[str]: ...
    def get_open_s_s_h_config_path(self) -> Property[str]: ...
    def get_proxy_command(self) -> Property[str]: ...
