-- Migration 018: admin runtime policy controls + audit trail (Priority 6 foundation)
-- Purpose:
-- - Store superuser-managed runtime policy values in Postgres (no code deploy needed for value changes)
-- - Provide audit history for policy changes (who/when/from/to/reason)

CREATE TABLE IF NOT EXISTS public.admin_runtime_policy (
  policy_key TEXT PRIMARY KEY,
  value_jsonb JSONB NOT NULL,
  value_type TEXT NOT NULL
    CHECK (value_type IN ('boolean', 'integer', 'number', 'string', 'object', 'array')),
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by UUID REFERENCES auth.users(id)
);

CREATE TABLE IF NOT EXISTS public.admin_runtime_policy_audit (
  audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  policy_key TEXT NOT NULL REFERENCES public.admin_runtime_policy(policy_key) ON DELETE CASCADE,
  old_value_jsonb JSONB,
  new_value_jsonb JSONB NOT NULL,
  changed_by UUID REFERENCES auth.users(id),
  changed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  reason TEXT
);

CREATE INDEX IF NOT EXISTS idx_admin_runtime_policy_audit_changed_at
  ON public.admin_runtime_policy_audit(changed_at DESC);

CREATE INDEX IF NOT EXISTS idx_admin_runtime_policy_audit_policy_key_changed_at
  ON public.admin_runtime_policy_audit(policy_key, changed_at DESC);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_trigger
    WHERE tgname = 'set_admin_runtime_policy_updated_at'
  ) THEN
    CREATE TRIGGER set_admin_runtime_policy_updated_at
    BEFORE UPDATE ON public.admin_runtime_policy
    FOR EACH ROW
    EXECUTE FUNCTION public.set_updated_at();
  END IF;
END $$;

ALTER TABLE public.admin_runtime_policy ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_runtime_policy_audit ENABLE ROW LEVEL SECURITY;

-- Service role writes via Edge Functions; no direct authenticated access.
REVOKE ALL ON public.admin_runtime_policy FROM anon, authenticated;
REVOKE ALL ON public.admin_runtime_policy_audit FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.admin_runtime_policy TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.admin_runtime_policy_audit TO service_role;

INSERT INTO public.admin_runtime_policy (policy_key, value_jsonb, value_type, description)
VALUES
  ('models.platform_default_model', '"claude-sonnet-4-5-20250929"'::jsonb, 'string', 'Platform baseline model fallback'),
  ('models.platform_default_temperature', '0.3'::jsonb, 'number', 'Platform baseline temperature fallback'),
  ('models.platform_default_max_tokens', '2000'::jsonb, 'integer', 'Platform baseline max tokens per block fallback'),
  ('worker.prompt_caching.enabled', 'true'::jsonb, 'boolean', 'Enable prompt caching by default for new runs'),
  ('worker.batching.enabled', 'true'::jsonb, 'boolean', 'Enable adaptive batching by default for new runs'),
  ('worker.batching.pack_size', '10'::jsonb, 'integer', 'Default target blocks-per-pack for new runs'),
  ('worker.batching.pack_size_max', '40'::jsonb, 'integer', 'Hard cap for pack size on new runs'),
  ('worker.batching.text_heavy_max_pack_size', '6'::jsonb, 'integer', 'Max pack size for text-heavy schemas on new runs'),
  ('worker.batching.context_window_tokens', '200000'::jsonb, 'integer', 'Context window budget used for pack construction'),
  ('worker.batching.output_reserve_tokens', '20000'::jsonb, 'integer', 'Reserved output budget used for pack construction'),
  ('worker.batching.tool_overhead_tokens', '2000'::jsonb, 'integer', 'Tool/prompt overhead budget used for pack construction'),
  ('worker.batching.max_output_tokens', '8192'::jsonb, 'integer', 'Per-call max output tokens for batched calls'),
  ('worker.batching.per_block_output_tokens', '200'::jsonb, 'integer', 'Estimated per-block output tokens for batching'),
  ('worker.claim_batch_size.default', '25'::jsonb, 'integer', 'Default queue claim batch size per worker request'),
  ('worker.claim_batch_size.min', '1'::jsonb, 'integer', 'Minimum queue claim batch size'),
  ('worker.claim_batch_size.max', '100'::jsonb, 'integer', 'Maximum queue claim batch size'),
  ('worker.max_retries', '3'::jsonb, 'integer', 'Max attempts before marking block overlay failed'),
  ('upload.max_files_per_batch', '25'::jsonb, 'integer', 'UI upload batch limit'),
  (
    'upload.allowed_extensions',
    '["md","markdown","docx","pdf","pptx","xlsx","html","htm","csv","txt"]'::jsonb,
    'array',
    'Allowed file extensions for ingest'
  )
ON CONFLICT (policy_key) DO NOTHING;
