from __future__ import annotations

# Source: E:\KESTRA-IO\plugins\plugin-meta\src\main\java\io\kestra\plugin\meta\facebook\enums\PostMetric.java

from enum import Enum
from typing import Any


class PostMetric(str, Enum):
    POST_REACTIONS_LIKE_TOTAL = "POST_REACTIONS_LIKE_TOTAL"
    POST_REACTIONS_LOVE_TOTAL = "POST_REACTIONS_LOVE_TOTAL"
    POST_REACTIONS_WOW_TOTAL = "POST_REACTIONS_WOW_TOTAL"
    POST_REACTIONS_HAHA_TOTAL = "POST_REACTIONS_HAHA_TOTAL"
    POST_REACTIONS_SORRY_TOTAL = "POST_REACTIONS_SORRY_TOTAL"
    POST_REACTIONS_ANGER_TOTAL = "POST_REACTIONS_ANGER_TOTAL"
    POST_IMPRESSIONS = "POST_IMPRESSIONS"
    POST_ENGAGED_USERS = "POST_ENGAGED_USERS"
    POST_CLICKS = "POST_CLICKS"
    POST_REACTIONS_BY_TYPE_TOTAL = "POST_REACTIONS_BY_TYPE_TOTAL"
