from __future__ import annotations

from typing import Any, Protocol

from engine.core.models.property.property import Property


class NatsConnectionInterface(Protocol):
    def get_url(self) -> str: ...
    def get_username(self) -> Property[str]: ...
    def get_password(self) -> Property[str]: ...
    def get_token(self) -> Property[str]: ...
    def get_creds(self) -> Property[str]: ...
